### PR TITLE
change the header text from NA to TFUG Jalandhar

### PR DESCRIPTION
**Pull request by Syc0ms**
Changed the title from NA to TFUG Jalandhar in index.html

issue #4 
image

### CODE REVIEW

**Comment by AmanNegi** [comment]
@Syc0ms It's good to add preview screenshots to explain what you really did. Also not a good idea to keep the description of PR empty. (Tag the issue as well #4)

**Comment by Syc0ms** [comment]
can you check it now?
Its my first PR in github and open-source, sorry for mistakes haha:)

**Comment by Syc0ms** [comment]
If you have examples of PR, i would like to see it. For opening PR's in future

**Comment by AmanNegi** [comment]
Looks good enough for now. Regarding demo I'll link one below.

https://github.com/AppFlowy-IO/AppFlowy/pull/6130

> Note how they mention `closes`.

**Comment by AmanNegi** [comment]
Thanks for the contribution.

Congratulations on your first PR. ✨🙌

**Comment by Syc0ms** [comment]
Thanks!

**Pull request merged**
