### PR TITLE
Fixed issues in factorial, oddeve, and sum.

### PR DESCRIPTION
**Pull request by usefmahmud**
Solved issues #5, #7, #8.
- In factorial I changed the initial value of `fact` to **1**.
- In sum added the variable `c` to the input statement.
- In oddeve used the mod **%** instead of division by 2

### CODE REVIEW

**Comment by usefmahmud** [comment]
@AmanNegi 
Can you please accept the PR?

**Comment by AmanNegi** [comment]
Hey @usefmahmud, thanks for the contribution ✨🙌

I'd love to know how did you explore about this repository.

**Comment by usefmahmud** [comment]
I found it across https://goodfirstissues.com. And really thank you for this initiative

**Comment by AmanNegi** [comment]
Great work @usefmahmud. Thanks for the contribution. 🙌🌟

> A suggestion from me would be to keep a meaningful name for each branch. Also it's a good idea to solve one issue using one PR(not always though, if the issues are related it's fine).

Again thanks, and I hope you were able to build some confidence. Cheers 🥂🥳

**Comment by usefmahmud** [comment]
I will keep it in mind. Thanks for you feedback 🙏

**Pull request merged**
